apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wstd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0018-tenant/ci1t-43256-0018-app/devfile-sample-wstd@sha256:c9cab389731098c1d0483dc3c3894222b73719be5c72f77d42d6e3542b0f2851
        name: my-nodejs
        resources: {}
status: {}
